-- Telegram GitCode Hub core schema
-- Secrets stay server-side. Telegram identity is represented by telegram_user_id.

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  telegram_user_id bigint not null unique,
  username text,
  first_name text not null,
  last_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  owner_id bigint not null references public.users(id) on delete cascade,
  name text not null,
  description text,
  default_branch text not null default 'main',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(owner_id, name)
);

create table if not exists public.files (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  path text not null,
  content text not null default '',
  size_bytes integer not null default 0,
  updated_at timestamptz not null default now(),
  unique(project_id, path)
);

create table if not exists public.commits (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  author_id bigint not null references public.users(id) on delete restrict,
  message text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.commit_files (
  commit_id bigint not null references public.commits(id) on delete cascade,
  file_id bigint not null references public.files(id) on delete cascade,
  content text not null,
  primary key(commit_id, file_id)
);

create index if not exists projects_owner_idx on public.projects(owner_id);
create index if not exists files_project_idx on public.files(project_id);
create index if not exists commits_project_idx on public.commits(project_id, created_at desc);

alter table public.users enable row level security;
alter table public.projects enable row level security;
alter table public.files enable row level security;
alter table public.commits enable row level security;
alter table public.commit_files enable row level security;

-- Access is intentionally not opened to the anonymous browser client yet.
-- API routes will use a server-side service role after Telegram identity is validated.
